llm:
  default_provider: openai
  providers:
    openai:
      models:
        - gpt-4
        - gpt-3.5-turbo
    anthropic:
      models:
        - claude-3-sonnet-20240229
        - claude-3-haiku-20240307
context:
  max_files: 100
  max_file_size: 100000
  sources:
    - type: directory
      path: ./src
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
    - type: file
      path: ./README.md
security:
  rate_limit:
    window_ms: 900000
    max_requests: 100
